language: node_js
node_js:
  - 12

before_deploy:
  - npm install -g ask-cli

deploy:
  provider: script
  skip_cleanup: true
  script: mkdir -p ~/.ask; echo '{"profiles":{}}' > ~/.ask/cli_config; npm run deploy:prod
  on: master
